spring:
  application:
    name: gateway-service-zuul
server:
  port: 8880
#zuul:
#  routes:
#    api-a:
#      path: /producer/**
#      serviceId: spring-cloud-producer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/