spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rhwanxx/config-server
          search-paths:
          username: Rhwanxx
          password: qq19930202
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8800/eureka/   #注册中心eurka地址