spring:
  application:
    name: spring-cloud-congfig-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rhwanxx/config-server
          search-paths:
          username: Rhwanxx
          password:
server:
  port: 8001